// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tasks4U.Models;

#nullable disable

namespace Tasks4U.Migrations
{
    [DbContext(typeof(TasksContext))]
    [Migration("20221210081607_AddDesk")]
    partial class AddDesk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Tasks4U.Models.Desk", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Desks");
                });

            modelBuilder.Entity("Tasks4U.Models.Task", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeskID")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("FinalDate")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("IntermediateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TaskFrequency")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("DeskID");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Tasks4U.Models.Task", b =>
                {
                    b.HasOne("Tasks4U.Models.Desk", "Desk")
                        .WithMany()
                        .HasForeignKey("DeskID");

                    b.Navigation("Desk");
                });
#pragma warning restore 612, 618
        }
    }
}
